# ============= #
# === Build === #
# ============= #
FROM node:lts-alpine AS build

WORKDIR /service-frontend

# First retrieve the package.json and install all the dependencies.
# This eliminates the need for re-installing all of the packages when the application code changes.
COPY package*.json ./
RUN npm install

# Copy all of the source files into our image
COPY . ./

EXPOSE 8080

# Run the application
CMD ["npm", "run", "serve", "--", "--port", "8080"]
