name: "Build, test, and deploy the main branche"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      # Action setup
      - name: "Go to this branche"
        uses: actions/checkout@v2
      - name: "Setup NodeJS"
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      # Environment setup
      - name: "Create main property file"
        run: |
          touch .env
          echo "VUE_APP_BACKEND_URL=\"http://guyliangilsing.me:8086/api/v1\"" >> .env
      # Testing
      - name: "Install all packages"
        run: npm install
      - name: "Run tests"
        run: npm run test:unit
      - name: "Run static code analysis"
        run: npm run lint
      # Build docker image
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      # Deploy image to dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        run: |
            export DOCKER_BUILDKIT=0
            export COMPOSE_DOCKER_CLI_BUILD=0
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/adb-service-frontend:latest .
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/adb-service-frontend:latest
      - name: "Update deployment"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/docker/projects/attractions-database
            docker-compose down
            docker-compose pull
            docker-compose up -d
